# Generated by Django 3.2.4 on 2021-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_num', models.CharField(max_length=50)),
                ('vehicle_year_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('report', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=10)),
                ('injury', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='User/')),
                ('document', models.FileField(blank=True, null=True, upload_to='User/')),
            ],
        ),
    ]
