# Generated by Django 3.2.4 on 2021-07-04 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
